###Create empty GPOs###
New-GPO -Name "BMC Operational Users Policy"
New-GPO -Name "BMC Technical Users Policy"
New-GPO -Name "Certificate Enrollment Policy"
New-GPO -Name "Screen Saver Policy"
New-GPO -Name "Windows 10 Administrative Templates Policy"
New-GPO -Name "Windows 10 Audit Policy"
New-GPO -Name "Windows 10 Components Policy"
New-GPO -Name "Windows 10 Local Policy"
New-GPO -Name "Windows 10 Services Policy"
New-GPO -Name "Windows 2019 Administrative Templates Policy"
New-GPO -Name "Windows 2019 Audit Policy"
New-GPO -Name "Windows 2019 Components Policy"
New-GPO -Name "Windows 2019 Domain Controller Administrative Templates Policy"
New-GPO -Name "Windows 2019 Domain Controller Windows Components Policy"
New-GPO -Name "Windows 2019 Local Policy"
New-GPO -Name "Windows 2019 Servers Policy"
New-GPO -Name "Windows 2019 Services Policy"
New-GPO -Name "Windows EAP Policy"
New-GPO -Name "Windows Firewall Policy"
New-GPO -Name "Windows LAPS Policy"
New-GPO -Name "Windows Policy Password"
New-GPO -Name "Windows RDP Certificate Policy"
New-GPO -Name "Disable Auto lock Screen Policy"
New-GPO -Name "Windows BitLocker Policy"
New-GPO -Name "DC Local Policy"
New-GPO -Name "VM VBS Policy"
